### ISSUE TITLE
Multi NVME Support for RAID?

### ISSUE THREAD

**Issue by Dviros** [turing-machines/BMC-Firmware#101]
Hello!
I'm looking for a way to link a single node to 4 NVME drives for software RAID purposes.
Any idea if this is achievable?

Many thanks!

**Comment by daniel-kukiela** [comment]
Hi!
The Mini PCIe slot carries only a single PCIe lane and I haven't heard of any Mini PCIe controllers that can expose 4 NVMe ports.
What you might try to do is to use a Mini PCIe to PCIe adapter and some full-size PCIe card with a PCIe switch. This card would have to contain a PCIe switch.
The switch would have to be able to work with a single PCIe 2.0 lane.
Please also keep in mind that this will share a single PCIe 2.0 lane and the theoretical max bandwidth would be 500MB/s. In this case, it might be easier and cheaper to use a Mini PCIe to 4-port SATA controller and use 4x SATA SSD (which also should saturate 500MB/s of bandwidth).
