### ISSUE TITLE
Get rid of Python3 dependency

### ISSUE THREAD

**Issue by svenrademakers** [turing-machines/BMC-Firmware#109]
**Is your feature request related to a problem? Please describe.**
Since 1.1.0, the binary size increased by over 20MiB, with python3 contribution of 19MiB.

**Describe the solution you'd like**
Investigate which package is pulling in Python, and see if we can replace it with something lighter

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by gjrtimmer** [comment]
The removal of the pyhton dependecy also makes using ansible on the BMC host not possible now.
Is there a way for a user to manually install python again?
