### ISSUE TITLE
tpi -m: stdout node number is zero-indexed

### ISSUE THREAD

**Issue by cprima** [turing-machines/BMC-Firmware#112]
**Describe the bug**
off-by-one: tpi takes the argument `-n` from 1-4, the output of `tpi -n 3 -m` returns 0-3

**To Reproduce**
1. As per documentation https://docs.turingpi.com/docs/raspberry-pi-cm4-install-os-using-turing-pi2-cluster#flashing-from-a-command-line
2. When accessing the node's filesystem with `tpi -n 3 -m`
3. tpi returns on stdout: `booting node 2 into msd mode. please wait a moment..`

**Expected behavior**
The node integer of stdout should reflect the parameter

**Versions**
linux version= Linux turingpi 5.4.61 #1 SMP PREEMPT Fri Jul 28 18:47:02 UTC 2023 armv7l GNU/Linux
bmc version= 1.1.0

**Comment by svenrademakers** [comment]
fixed in latest in tpi repo https://github.com/turing-machines/tpi
