### ISSUE TITLE
Ability to format bmc SD card with supported filesystems

### ISSUE THREAD

**Issue by meierra** [turing-machines/BMC-Firmware#114]
I recently found that the SD card installed in my TuringPi2 was not formatted with a supported filesystem, I was able to use ssh and fdisk to create the partition, but no valid mkfs for the supported filesystem types was available, (I could only find mkfs.ubifs)

Would it be possible to include mkfs for the supported sdcard formats (exFAT, NTFS, FAT32, EXT4) and later possibly the ability to format the SDcard via the UI?

**Comment by svenrademakers** [comment]
I'm sorry for not getting back to you sooner. Your point is valid. We are tight regarding flash space, but this seems like low-hanging fruit.

**Comment by meierra** [comment]
Hi Sven,

All good on the timing, thanks for looking at this

Robert

**Comment by thz** [comment]
Also, having a mkfs.vfat would enable creation of /boot filesystem for rpi systems. This would allow installation of custom rpi systems, where you copy contents of /boot over the network (scp) instead of flushing the image.
