### ISSUE TITLE
Power and status LEDs stop working after upgrading to V1.1.0

### ISSUE THREAD

**Issue by mranest** [turing-machines/BMC-Firmware#115]
**Describe the bug**
Power and status LEDs stop working after upgrading to BMC firmware V1.1.0. Both work properly with v1.0.2.

**To Reproduce**
1. Upgrade to V1.1.0
2. See behaviour of LEDs

**Expected behavior**
After connecting TPi2 to power as soon as BMC finishes booting the status LED should light. The Power LED should light when a node is active.

**Screenshots**
None of the LEDs light up, no matter whether BMC or a node is active.

**Versions**
bmc version=V1.1.0

**Comment by crkochan** [comment]
Running `echo "1" > /sys/class/leds/fp:sys/brightness` on the BMC shell illuminates the power button LED connected to the P-LED terminals.

**Comment by svenrademakers** [comment]
thanks for reporting! PR is opened here:
https://github.com/turing-machines/tpi_rs/pull/36

and will be part of the next release
