### ISSUE TITLE
BMC firmware has rpcbind installed+running for no apparent reason?

### ISSUE THREAD

**Issue by CFSworks** [turing-machines/BMC-Firmware#13]
`rpcbind` is part of the port mapper system, which is perhaps best known for being used by NFS servers. I am not seeing any reason that it ought to be enabled here. It seems like it was included by accident.

Since memory and flash space is at a premium here (and since `rpcbind` can be leveraged in DDoS attacks), it should probably be removed unless there's a solid reason to keep it.

**Comment by ruslashev** [comment]
Fixed in #77
