### ISSUE TITLE
Add f2fs support to the BMC for more stable SD card operation.

### ISSUE THREAD

**Issue by j0ju** [turing-machines/BMC-Firmware#141]
**Is your feature request related to a problem? Please describe.**
As a user I like to have a a most stable BMC as it runs idle for the most time, faults are detected when not expected or needed, for example when flashing images or using the BMC for out-of-band access for the installed SBC modules.
One source of errors is the SD card used to store images.
The BMC is a long running system, the SD card is used for storing images.
ext[234] filesystems regular write to the same blocks on disks which makes it hard for the embedded flash transaction layer (FTL) to detect that even if discard or trim are supported by the used SD card. In the end the SD card has errors in case it is most needed.
f2fs is in contrast aware of typical strategies the of underlying FTLs of SD cards, nowadays used as RW storage FS in many android phones and other devices.

**Describe the solution you'd like**
Add support f2fs kernel and userland support to the BMC.

**Comment by j0ju** [comment]
@gjrtimmer, I do NOT refer to any errors here.
 
I LIKE this feature to support this F2FS included, as it showed in a larger number deployments less errors.
I am also happy to supply patches if there is interest.

@gjrtimmer regarding the issue hijack: yes `noatime` generates fewer writes than `relatime`, `relatime`is the default of the kernel (since 2.6.xx, where xx is the from upper 20ies or lower 30ies)
AFAIK there is no feature in the BMC app the uses the last access time AKA last usage, so it `noatime` is fine to be used.

**Comment by gjrtimmer** [comment]
@j0ju sorry my bad, i think it is always great to have community additions. If you can spare the time please submit some patches.

Regarding the noatime. AFAIK its not about if features are used. When any file is accessed then the access time of that file gets updated. But just to be sure I will dive some deeper into it. It has been a while so I want to make sure what the current state of all these options are. Especially since all the SSD advancement in the filesystems and kernel in the last few years.

**Comment by j0ju** [comment]
If the BMC app uses the last used time stamps on files or dirs, than `relatime` is needed, if the BMC app does not do this `noatime` is fine. The latter would reduce the amount of writes as for ext[234] FS any meta data update also requires a superblock update, although in ext4 these are delayed (like eventual consistency between super block and dentries).

**Comment by gjrtimmer** [comment]
@j0ju Agreed
