### ISSUE TITLE
wget and ca-certificates support

### ISSUE THREAD

**Issue by soxrok2212** [turing-machines/BMC-Firmware#149]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Enable wget and ca-certificates in kernel config so users can download files using wget.

**Additional context**
It's handy to use wget with SSL/TLS support to download files directly to the bmc.

**Comment by svenrademakers** [comment]
fixed in 76e1865eb7e2f4dc87d7b072502dfb98053badcd
