### ISSUE TITLE
v2.x: API documentation issue?

### ISSUE THREAD

**Issue by lintweaker** [turing-machines/BMC-Firmware#157]
**Describe the bug**
I just upgraded to BMC v2.05 and had to adjust my scripts to cope with the API changes.
It looks like either API the documentation is not updated or the API is not.

**To Reproduce**
For powering on a node, the API docs calls for:
/api/bmc?opt=power&type=set&node3=1

but this results in:
{"response":[{"result":"Missing `opt` parameter"}]}

but what works is:
/api/bmc?opt=set&type=power&node3=1

**Expected behavior**
API documentation matches the implementation (or vice versa)

**Versions**
bmc version= 2.05

**Comment by svenrademakers** [comment]
I've updated the documentation, thanks for reporting!
