### ISSUE TITLE
Add warning/confirmation before powering off a node

### ISSUE THREAD

**Issue by srcshelton** [turing-machines/BMC-Firmware#169]
**Is your feature request related to a problem? Please describe.**

_As_ an end-user of a TP2 system making use of installed nodes for long-running compute tasks,
_I would like_ the certainty of being protected from accidentally powering-off a running node or the wrong node)
_in order to_ minimise any time/work lost if a node is incorrectly powered-down.

**Describe the solution you'd like**

When the BMC Web UI 'Power' view is used to un-tick a node, there should be some form of confirmation before the power to that node is cut.

Ideally, the ticks on this page would be standard check-box controls, and there would be a separate "Apply" button.  On hitting "Apply", a confirmation dialog would be shown confirming what actions will be performed if allowed to continue, as well as giving an option to back-out.  This would also allow several nodes to be turned on or off at once.

**Describe alternatives you've considered**

Alternatively, if a two-stage select-then-apply approach isn't desired, at least a confirmation dialog being shown when powering-down a node would be much safer.  Note that confirmation could reasonably be skipping when powering-on a node which is currently off.

**Comment by svenrademakers** [comment]
fixed in e5f6158eeb61449a6b751e8febd27c6069cd56bb and upwards
