### ISSUE TITLE
Add BMC UI option to power-cycle node

### ISSUE THREAD

**Issue by srcshelton** [turing-machines/BMC-Firmware#171]
**Is your feature request related to a problem? Please describe.**

*As a* TP2 user,
*I would like to* be able to login to the BMC UI and power-cycle a node in one click (plus potentially another for confirmation) rather than having to click to power off the node (and confirm) and then wait a little, and then click to power back on
*so that* I can quickly and efficiently recover hung nodes.

**Describe the solution you'd like**
Alongside the power-state UI widgets, it would be great to have a "power-cycle" option (perhaps with a configurable down-delay? This might be overkill…) to automagically perform a power-down/wait/power-up sequence.

**Comment by svenrademakers** [comment]
fixed in e5f6158eeb61449a6b751e8febd27c6069cd56bb and onwards
