### ISSUE TITLE
BMC does not start if ipv6 is disabled

### ISSUE THREAD

**Issue by renanqts** [turing-machines/BMC-Firmware#174]
**Describe the bug**
bmcd cannot start if ipv6 is disabled.

```
# bmcd --config config.yaml
2024-01-16T19:57:58.207Z INFO  [bmcd] Turing Pi 2 BMC Daemon v2.0.5
Error: Cannot assign requested address (os error 99)
```

**To Reproduce**

Disable ipv6 via `sysctl.conf`, and restart
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

**Expected behavior**
it should bind ipv4

**Versions**
linux version= Linux turingpi 5.4.61 #1 SMP PREEMPT Tue Nov 28 13:52:46 UTC 2023 armv7l GNU/Linux
bmc version= 2024-01-16T19:58:47.969Z INFO  [bmcd] Turing Pi 2 BMC Daemon v2.0.5

**Additional context**

**Comment by svenrademakers** [comment]
fixed by https://github.com/turing-machines/bmcd/commit/992c5133474172a0034092642955fe350cdaa4f2
