### ISSUE TITLE
Switch of case fan when all nodes are powered off

### ISSUE THREAD

**Issue by meierra** [turing-machines/BMC-Firmware#53]
As a user I would like the board to go to a fully off state when all nodes are powered off, currently the fans keep running once all nodes are powered down.

**Comment by gjrtimmer** [comment]
@svenrademakers could you point me in the direction where to look regarding to control the power to the main fan pin? I want to see if I can make a pull request for it.

**Comment by svenrademakers** [comment]
on 2.5 boards, the fan is connected to the ATX voltage regulator. which switches off when the nodes switch off
