### ISSUE TITLE
Kubernetes Device plugin

### ISSUE THREAD

**Issue by svenrademakers** [turing-machines/BMC-Firmware#58]
TBD; Can we do something on the BMC that would help Kubernetes users?

**Comment by gclawes** [comment]
ClusterAPI provider would be cool, eventually.

**Comment by j0ju** [comment]
If the BMC OS would use the IP address 169.254.169.254 and its IPv6 pendants you could also bootstrap the OS image cloud-like with cloud-init if included into the image that is written to storage/SD card/NVMe/etc.
Unluckily the storage portion of the ClusterAPI provider would be somewhat limited.
