### ISSUE TITLE
Bug web interface: IP field shows garbage on IPv6 only networks

### ISSUE THREAD

**Issue by No0ne** [turing-machines/BMC-Firmware#79]
see attached screenshot:
<img width="1123" alt="bug" src="https://github.com/turing-machines/BMC-Firmware/assets/716129/7bd0fcea-f6d4-45e4-9f2c-460c3c57aafc">

**Comment by svenrademakers** [comment]
Hi @No0ne,

Are you able to tell a bit more about your setup? how to reproduce this issue?
Thanks!

**Comment by No0ne** [comment]
To reproduce connect the TuringPi to a v6-only network (no dhcp, no static ipv4).
As you can see in the terminal to the right on the screenshot there is no ipv4 on eth0.

**Comment by No0ne** [comment]
This is fixed on Version 2.x!
