### ISSUE TITLE
tpi tool v2

### ISSUE THREAD

**Issue by svenrademakers** [turing-machines/BMC-Firmware#86]
there will be a new tpi tool that replaces the old tool. Its not required to make an identical CLI to the old one, we want to have an interface which provides the best user experience. This tpi tool will be a simple HTTP client that executes Rest commands to the redfish interface of the BMC.

note: building and deploying the tpi tool on target is not required to complete this task.

# Acceptance Criteria

- [x] the tpi tool builds for windows, mac, linux
- [ ] the tpi tool does a SSDP discovery to find the Redfish service IP.
- [ ] If there are multiple redfish services available on the network, pick the first one
- [x] the user can pass a custom URL to the tpi tool to select a specific bmc.
- [x] the tpi tool is created in a new repository.
- [x] the tpi tool can shutdown the bmc, power on/off nodes and select a USB route

**Comment by svenrademakers** [comment]
created a new repo for this, see: https://www.github.com/turing-machines/tpi

**Comment by gjrtimmer** [comment]
@svenrademakers I see that the new TPI tool is written in `rust` is this mandatory? Due to multi arch I was thinking in contributing with golang. Can I give it a try or is `rust` a must?

**Comment by svenrademakers** [comment]
Go is probably the best choice, given this tool only does some API calls.  But a strong argument exists to keep everything in the same language/ecosystem. I don't want to make an exception for this case. 

Secondly, I will probably be the one maintaining this, and i wrote like 10 lines of go code in my life. Even though i would not mind learning new things, I want to prevent the potential headaches for now ;) 

At last, I'm almost finished coding this in Rust. you can take a look at: https://github.com/turing-machines/tpi

**Comment by svenrademakers** [comment]
`tpi` tool is implemented based on the legacy API. See https://github.com/turing-machines/tpi. The remaining action points are moved to a new ticket: https://github.com/turing-machines/tpi/issues/1
