### ISSUE TITLE
documentation issue: location of usb drivers to flash BMC

### ISSUE THREAD

**Issue by mjmenger** [turing-machines/BMC-Firmware#92]
In the [documentation to flash the BMC .img file](https://help.turingpi.com/hc/en-us/articles/8686945524893-Baseboard-Management-Controller-BMC-), there is a requirement to install "unsigned UsbDrivers (located in UsbDriver folder)." 

Where is the UsbDriver folder?

**Comment by svenrademakers** [comment]
I only have phoenix suit 1.10 at hand, not sure if the names changed in later versions.

* go to device manager, and locate the unknown device corresponding to the TP
![1](https://github.com/turing-machines/BMC-Firmware/assets/3875285/88d1d4ca-d2cf-4226-b1f6-2a9a47d48ac2)
* right click 'update drivers'
* browse my computer for drivers
* then browse to the PhoenixSuit installation folder and open the /Drivers subfolder
![2](https://github.com/turing-machines/BMC-Firmware/assets/3875285/cc18bfc9-de2d-4a6b-b49f-ccb86dff656e)
* click next 

This should be all to install the driver needed for phoenix suit.
The documentation is getting a bit of an overhaul at the moment, so hopefully we are able to have a more elaborate tutorial on this soon. Let me know if you still have any questions

**Comment by ruslashev** [comment]
BTW, you can skip a step and install driver without waiting for "Unknown device" to show up:

![Screenshot 2023-07-06 223026](https://github.com/turing-machines/BMC-Firmware/assets/1902096/01513916-484a-4c0f-ac02-beebe4d3776b)

**Comment by mjmenger** [comment]
> BTW, you can skip a step and install driver without waiting for "Unknown device" to show up:
> 
> ![Screenshot 2023-07-06 223026](https://user-images.githubusercontent.com/1902096/251544147-01513916-484a-4c0f-ac02-beebe4d3776b.png)

This was very helpful for me.
